# Generated by Django 5.2.17 on 2026-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_drive_hours', models.FloatField(default=0.0)),
                ('log_days', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
